#!/usr/bin/env python2

from bs4 import BeautifulSoup
import re
import requests
import sys

def validateArgument():
    try:
        pattern = re.compile("^((https?)\:\/\/)?((www\.)?youtube\.com|youtu\.?be)\/user\/.+$")
        if pattern.match(sys.argv[1]):
            return sys.argv[1] + '/videos'
        else:
            return "https://www.youtube.com/user/" + sys.argv[1] + '/videos'
    except:
        print("Lack of argument!")
        sys.exit(1)

def prettify(htmlResponse):
    soup = BeautifulSoup(htmlResponse, 'html.parser')
    for title in soup.find_all('h3', {'class': 'yt-lockup-title'})[:5]:
        video = title.contents[0]
        print("{0} - https://www.youtube.com{1}".format(video['title'], video['href']))

def getLatestVideosList():
    ytname = validateArgument()

    r = requests.get(ytname)
    if r.status_code == 200:
        prettify(r.text)
    else:
        print("404")

def main():
    ytname = validateArgument()
    getLatestVideosList()

if __name__ == "__main__":
    main()
